site_name: StoreCast
site_author: "Daksh Vanshaj"

nav:
  - Home: index.md
  - Business Context: 
      - Report: 01_business_context.md
      - Business Metrics: 01a_business_metrics_math.md
      - Baseline Model: ./notebooks_docs/01_baseline.ipynb
  - Data Pipelines:
      - Bronze Ingestion: scripts_docs/ingest_bronze_doc.md
      - Silver Transformation: scripts_docs/clean_silver_doc.md
  - Data Architecture:
      - Tech Stack & Tradeoffs: 02_architecture_tradeoffs.md
  - Data Analysis:
      - Bronze EDA: ./notebooks_docs/02_bronze_eda.ipynb

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  primary: teal
  accent: amber
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.instant

plugins:
  - search
  - mkdocs-jupyter
  - mermaid2

repo_url: https://github.com/dakshvanshaj/storecast
repo_name: StoreCast

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dakshvanshaj

    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/daksh-vanshaj-9a9650344/
